site_name: PS Documentation
site_description: 'Test documentation'
copyright: Copyright Product Science Inc. All rights reserved.

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Essentials Steps: essentials-steps.md
  - Working with PS tool: working-with-ps-tool.md
  - Dictionary: dictionary.md

theme:
  name: material
  # custom_dir: overrides
  font:
    text: Manrope
    code: Manrope
  palette:
    primary: blue grey
  # palette:
  #   # Light mode
  #   # media: "(prefers-color-scheme: light)"
  #   - scheme: default
  #     primary: white
  #     accent: teal
  #     toggle:
  #       icon: material/toggle-switch-off-outline
  #       name: Switch to dark mode
  #   # Dark mode
  #   - media: "(prefers-color-scheme: dark)"
  #     scheme: slate
  #     primary: black
  #     toggle:
  #       icon: material/toggle-switch
  #       name: Switch to light mode
  # include_search_page: false
  language: en
  features:
    # - navigation.tabs
    # - navigation.sections
    # - navigation.path
    - navigation.instant
    - navigation.expand
    - navigation.top
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.indexes
    - navigation.tracking
    - search.suggest
    - toc.integrate

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      permalink: #
  - footnotes
  - admonition
  - attr_list
  - pymdownx.highlight:
      use_pygments: true
      pygments_style: 'default'
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - glightbox:
     loop: false
     effect: zoom
    #  slide_effect: none
     auto_caption: false
  - minify:
      minify_html: false
  - search